version: '3.8'

services:
  web:
    build: .
    # For local development, we often just run the dev server so tailwind rebuilding works easily,
    # or you can run gunicorn with autoreload. Let's use the standard manage.py for local docker.
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://user:password@db:5432/django_db
      - SECRET_KEY=django-insecure-testkey
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
