# Generated by Django 6.0.4 on 2026-05-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AchievementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("points", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("address", models.CharField(max_length=512)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Nisavski", "Nisavski"),
                            ("Borski", "Borski"),
                            ("Zajecarski", "Zajecarski"),
                            ("Toplicki", "Toplicki"),
                            ("Podunavski", "Podunavski"),
                            ("Kosovo i Metohija", "Kosovo i Metohija"),
                            ("Grad Beograd", "Grad Beograd"),
                        ],
                        default="Grad Beograd",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlobalManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=512)),
                ("telephone", models.CharField(max_length=15)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("schools", models.ManyToManyField(to="merit.school")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SchoolManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=512)),
                ("telephone", models.CharField(max_length=15)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="merit.school"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=512)),
                ("telephone", models.CharField(max_length=15)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="merit.school"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merit.achievementtype",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="merit.student",
                    ),
                ),
            ],
        ),
    ]
