# Generated by Django 6.0.4 on 2026-05-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
