# Generated by Django 6.0.4 on 2026-05-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="region",
            field=models.CharField(
                choices=[
                    ("Nisavski", "Nisavski"),
                    ("Borski", "Borski"),
                    ("Zajecarski", "Zajecarski"),
                    ("Toplicki", "Toplicki"),
                    ("Podunavski", "Podunavski"),
                    ("Kosovo i Metohija", "Kosovo i Metohija"),
                    ("Grad Beograd", "Grad Beograd"),
                ],
                default="Grad Beograd",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="merit.student",
            ),
        ),
    ]
