# Generated by Django 6.0.4 on 2026-05-29 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merit', '0002_achievement_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalmanager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='globalmanager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='globalmanager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='schoolmanager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='schoolmanager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='schoolmanager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='globalmanager',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolmanager',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
